### ISSUE TITLE
Formatter either not fixing errors or outputting failures

### ISSUE THREAD

**Issue by pardom** [shyiko/ktlint#17]
For this branch: https://github.com/pardom/redux-kotlin/pull/13

**Comment by shyiko** [comment]
Hi @pardom. Just tried ktlint@0.2.2 on that branch. I'm only seeing "Unexpected indentation" (it looks like lib/src/main/kotlin/redux/Middleware.kt is using tabs instead of spaces for indentation). ktlint isn't going to fix that particular violation per https://github.com/shyiko/ktlint/issues/8#issuecomment-241490841. So as far as I see it everything works the way it should. Let me know if I'm missing something. Thanks!

**Comment by shyiko** [comment]
FYI: https://github.com/shyiko/ktlint/blob/master/changelog.md

**Comment by pardom** [comment]
Ah, I missed that. Thanks!
