### ISSUE TITLE
Maven plugin dies with ClassCastException

### ISSUE THREAD

**Issue by seanf** [shyiko/ktlint#22]
I'm basically using the sample config from the readme, except:

1. I commented out `<phase>verify</phase>`.
2. I'm executing with `mvn antrun:run@ktlint`, not `mvn verify`. (I'm assuming ktlint doesn't care about binaries, just source.)
3. Using maven-antrun-plugin:1.8, not 1.7.

I've got kotlin-maven-plugin 1.0.6 in my project.

> [INFO] --- maven-antrun-plugin:1.8:run (ktlint) @ server ---
> [INFO] Executing tasks
> 
> ktlint:
>    [ktlint] Exception in thread "main" java.lang.ClassCastException: org.jetbrains.kotlin.lexer.KtKeywordToken cannot be cast to org.jetbrains.kotlin.com.intellij.psi.tree.IElementType
>    [ktlint]     at com.gihub.shyiko.ktlint.ruleset.standard.SpacingAfterKeywordRule.<init>(SpacingAfterKeywordRule.kt:22)
>    [ktlint]     at com.gihub.shyiko.ktlint.ruleset.standard.StandardRuleSetProvider.get(StandardRuleSetProvider.kt:8)
>    [ktlint]     at com.github.shyiko.ktlint.Main.main(Main.kt:186)

**Comment by shyiko** [comment]
Hey Sean.

That error is thrown due to due different versions of kotlin compiler on the maven.plugin.classpath. In your case, detekt is bringing 1.0.5-2 (https://github.com/zanata/zanata-platform/blob/kotlin/server/pom.xml#L2068) while ktlint depends on 1.0.6. You have several options: 
1. remove either ktlint or detekt (which is something I recommend doing) 
2. use `<exclusions>` to exclude org.jetbrains.kotlin:kotlin-compiler:1.0.5-2 (there is no guarantee detekt will still work though) 
3. use multiple profiles to separate ktlint and detekt.

Let me know if you need anything else. Cheers!

**Comment by seanf** [comment]
Okay, thank you very much for digging into it, @shyiko!
