### ISSUE TITLE
Alphabetical import ordering

### ISSUE THREAD

**Issue by JLLeitschuh** [shyiko/ktlint#236]
I just realized that Ktlint doesn't seem to care about the ordering of imports.
Should they be alphabetized by Ktlint?

**Comment by shyiko** [comment]
Hey Jonathan. 
We have [ImportOrderingRule](https://github.com/shyiko/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/ImportOrderingRule.kt) but it's not enabled due to the https://github.com/shyiko/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/StandardRuleSetProvider.kt#L13. We need either to find a way to reconcile the differences (between the Intellij and AS) or move that rule into a separate ruleset.

**Comment by gabrielittner** [comment]
Do you have an example of what exactly the difference is?

**Comment by shyiko** [comment]
I believe the order of (at least) static imports was different. I can't be certain though, I have to go back and recheck. If IntelliJ/AS's Ctrl+Alt+O ("Optimize Imports...") can be made to produce the same output - we can reconsider turning it back on.

**Comment by gabrielittner** [comment]
The Android style guide says it should be a single ASCII sorted list. From what I can see that's what I get by using optimize imports in AS.

**Comment by shyiko** [comment]
Closing as a duplicate, https://github.com/shyiko/ktlint/issues/189.
