### ISSUE TITLE
--format add an extra line at the end of the file

### ISSUE THREAD

**Issue by bethcutler** [shyiko/ktlint#282]
When formatting a file that (correctly) has a newline at the end, the formatter will sometimes add an extra newline (which causes the formatted file to fail when run through the linter later).

From what I can tell, this happens only when using the --stdin flag, and with "insert_final_newline = true" in the .editorconfig file.

**Comment by shyiko** [comment]
Thank you for taking the time to track it down! 
`println(formattedFileContent)` does look like the culprit here.

Regarding `insert_final_newline`:
[editorconfig.org](https://editorconfig.org/) says 
> set to true to ensure file ends with a newline when saving and false **to ensure it doesn't**.

In other words, 
insert_final_newline=true == file should end with \n (insert if missing, do nothing otherwise)
insert_final_newline=false == there should be no \n at the end of file (remove if present)
insert_final_newline=unset == do nothing (preserve whatever is there)
