### ISSUE TITLE
Make more clear in front page README about support of official coding conventions

### ISSUE THREAD

**Issue by binkley** [shyiko/ktlint#284]
https://kotlinlang.org/docs/reference/coding-conventions.html

I'd be nice if the front page README was more clear about supporting the official coding conventions out of the box, and if ktlint defaults to those without further configuration.

**Comment by shyiko** [comment]
Hi @binkley.
 
While ktlint is [based on the official Kotlin style guide](https://github.com/shyiko/ktlint#option-2) it's a little bit more strict (max number of blank lines is 1 instead of 2, wildcard imports/redundant semicolons/empty lines before `}` are prohibited) (https://github.com/shyiko/ktlint#-with-intellij-idea).

I'll update the README to make it clear. :bowing_man:

**Comment by camsteffen** [comment]
This is the first thing I wanted to know about ktlint.
