### ISSUE TITLE
Problematic imports

### ISSUE THREAD

**Issue by gmrandom** [shyiko/ktlint#39]
The package has multiple imports from the org.jetbrains.kotlin.com.intellij namespace, but I can't seem to find how to resolve these in the Kotlin codebase.

For example:

https://github.com/shyiko/ktlint/blob/master/ktlint-ruleset-standard/src/main/kotlin/com/github/shyiko/ktlint/ruleset/standard/SpacingAfterKeywordRule.kt#L4

Should refer to:
https://github.com/JetBrains/intellij-community/blob/master/platform/core-api/src/com/intellij/lang/ASTNode.java

The correct imports seem to be simply com.intellij without org.jetbrains.kotlin prepended. Am I missing something?

**Comment by shyiko** [comment]
Hi. 

`kotlin-ruleset-standard` depends on 
```xml
<dependency>
  <groupId>org.jetbrains.kotlin</groupId>
  <artifactId>kotlin-compiler-embeddable</artifactId>
  <version>${kotlin.version}</version>
</dependency>
 ```
(through `com.github.shyiko.ktlint:ktlint-core`).  

`org.jetbrains.kotlin:kotlin-compiler-embeddable` is an "[uber](https://maven.apache.org/plugins/maven-shade-plugin/examples/includes-excludes.html) jar" with all the dependencies included (`com.intellij.lang` [relocated](https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html) under `org.jetbrains.kotlin` to to avoid conflicts). 

`ktlint` uses `kotlin-compiler-embeddable` instead of `kotlin-compiler` simply because gathering all the dependencies used by the `org.jetbrains.kotlin:kotlin-compiler` was a living hell last time I checked.

**Comment by gmrandom** [comment]
Thanks for the explanation!
