### ISSUE TITLE
How do you develop ktlint?

### ISSUE THREAD

**Issue by bolinfest** [shyiko/ktlint#83]
I cloned the repo, but there is no `.idea` directory, so it doesn't seem like it imports cleanly into IntelliJ. I ended up telling IntelliJ to create a project from the root `pom.xml`, but the `.idea` folder it created is not in `.gitignore`, so now I can't make any local commits without either checking in my `.idea` folder or making local changes to `.gitignore`.

Further, once I have the project in IntelliJ, it seems to generally recognize the project structure, but it's not great. For example, when I open `NoVarRuleTest.kt` and right-click in the editor, there is no option to run the test.

This does not seem to be covered in https://github.com/shyiko/ktlint/blob/master/CONTRIBUTING.md. Similarly, the only advice that https://github.com/shyiko/ktlint/blob/master/README.md provides with respect to contributing is to run `./mvnw`.

**Comment by shyiko** [comment]
Hi @bolinfest 

`.idea` is in my `~/.gitignore_global` (along with the rest of OS/editor-specific entries). You can either do the same (which is generally recommended practice) or don't bother and add `.idea` to the `.gitignore` (if you send a PR with `.gitignore` updated I **won't** ask you to revert the change, don't worry). 

Importing project given `pom.xml` is universal and works pretty much any in IDE (I use Intellj IDEA). The reason `NoVarRuleTest.kt` behaves differently from the rest of the project is because `ktlint-ruleset-template` directory does not contain `pom.xml` (in other words, it's not a Maven module; it's just an example of the ruleset that people can use as a starting point). I treat that directory as a separate project whenever I need to make changes to it (especially considering that it's gradle-based).
